language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
before_install:
    - phpenv config-rm xdebug.ini || true
    - composer clear-cache

install:
  - composer install
  - if [[ "$DEPS" = 'high' || "$DEPS" = 'dev' ]]; then travis_retry composer $DEFAULT_COMPOSER_FLAGS update; fi
  - if [[ "$DEPS" = 'high' ]]; then composer require $DEFAULT_COMPOSER_FLAGS --prefer-stable --update-with-dependencies vimeo/psalm; fi
  - if [[ "$DEPS" = 'low' ]]; then travis_retry composer $DEFAULT_COMPOSER_FLAGS --prefer-lowest --prefer-stable update; fi
  - if [[ "$DEPS" = 'stable' ]]; then travis_retry composer $DEFAULT_COMPOSER_FLAGS --prefer-stable update; fi
  - ./vendor/bin/psalm --version

script: composer check

env:
    matrix:
        - DEPS="low"
        - DEPS="high"
        - DEPS="stable"
        - DEPS="dev"
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-suggest"

cache:
  directories:
    - ./vendor

allow_failures:
    - php: 7.1
      env: DEPS="dev"
    - php: 7.2
      env: DEPS="dev"
    - php: 7.3
      env: DEPS="dev"
    - php: 7.4
      env: DEPS="dev"
